### ISSUE TITLE
What's?

### ISSUE THREAD

**Issue by DarkFiveNess** [Digiwind/Digiwind-Videos#2]
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    bot = discord.Bot()
AttributeError: module 'discord' has no attribute 'Bot'

`
import discord
from discord.ui import TextInput, Modal
bot = discord.Bot()
`

**Comment by Digiwind** [comment]
Make sure you have Pycord installed. If you have Discord.py installed - or some other Python Discord API library, make sure you uninstall it or enter a virtual environment.

**Comment by grasshaussoftware** [comment]
i tried to use pycord but its giving me an error. it was working (sort of) with discord.py except that i would get two ticket creation button prompts instead of just one when i invoked with the slash command.

`Traceback (most recent call last):
  File "/home/deusopus/ticketing.py", line 3, in <module>
    from discord import app_commands, utils
ImportError: cannot import name 'app_commands' from 'discord' (/home/deusopus/.local/lib/python3.10/site-packages/discord/__init__.py)
`
